locations:
  spawn:
    world: world
    x: -224
    y: 68
    z: 240
  waiting-area:
    world: world
    x: 10
    y: 121
    z: 100

messages:
  team-won: "&aYou're team has won."
  team-lost: "&cYou're team has lost."

  players-needed: "&e{amount} more players is needed." ## action bar
  game-is-full: "&cGame is full, Cannot Join!"
  cannot-join-game: "&cLeave current game before joining a new game."
  countdown: "&aGame starting in %time%"
  king-selected: "&aYou are the &6&lKing"
  cannot-leave-game: "&cYou are not in a game!"
  invalid-game: "&c&l{player} tried to join: Game - {game} but it doesn't exist"
  game-registered: "&aGame: {game} has been registered"
  game-limit-reached: "&cCannot register: {game}. The game limit has been reached"
  captured-flag: "You captured a flag"
  game-display:
    - "&a&lGames"
    - "{GAME-DISPLAY} &f&l- &a&lGame: &f{gameName} &l- &a&lSize: &f{size}"

# How much coins you will get per kill
coins-per-kill: 4
# How much coins you will get per win
coins-per-win: 20

database:
  enable: false
  user: root
  pass: password1234
  database: ctf
  host: localhost
  port: 3306
  ssl: true