countdown: "&aGame starting in %time%"
king-selected: "&aYou are the &6&lKing"
game-display:
  - "&a&lGames"
  - "{GAME-DISPLAY} &f&l- &a&lGame: &f{gameName} &l- &a&lSize: &f{size}"

spawn:
  world: world
  x: 0
  y: 70
  z: 0

waiting-area:
  world: world
  x: 10
  y: 100
  z: 100

database:
  enable: false
  user: root
  pass: password1234
  database: ctf
  host: localhost
  port: 3306
  ssl: false